"""An index of every launchable application on this machine.

``Get-StartApps`` is the authoritative source: it reports both classic Win32
Start Menu entries and packaged/Store apps, each with an AppID that
``shell:AppsFolder`` can launch uniformly. That single mechanism means Jarvis
launches everything the same way you would from the Start menu -- as your
user, with no elevation.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import threading
import time
from dataclasses import asdict, dataclass
from pathlib import Path

from rapidfuzz import fuzz, process

from .config import APP_INDEX_PATH, load
from .log import get
from .winutil import NO_WINDOW, powershell_json

log = get("jarvis.appindex")

# Start Menu clutter that is never what someone means by "open X".
_JUNK = re.compile(
    r"^(uninstall|remove|help|documentation|readme|release notes|"
    r"website|homepage|support|manual|license|changelog)\b",
    re.IGNORECASE,
)


@dataclass
class AppEntry:
    name: str
    app_id: str
    kind: str  # "packaged" | "win32" | "url"

    @property
    def is_junk(self) -> bool:
        return bool(_JUNK.match(self.name))


class AppIndex:
    def __init__(self) -> None:
        self._entries: list[AppEntry] = []
        self._lock = threading.RLock()
        self._refreshed_at: float = 0.0

    # -- lifecycle ---------------------------------------------------------

    def load_cache(self) -> bool:
        if not APP_INDEX_PATH.exists():
            return False
        try:
            raw = json.loads(APP_INDEX_PATH.read_text(encoding="utf-8"))
            with self._lock:
                self._entries = [AppEntry(**e) for e in raw.get("entries", [])]
                self._refreshed_at = raw.get("refreshed_at", 0.0)
            log.info("loaded %d apps from cache", len(self._entries))
            return bool(self._entries)
        except Exception:
            log.warning("app index cache unreadable; will rebuild")
            return False

    def ensure(self) -> None:
        """Load from cache, rebuilding if missing or older than a day."""
        if not self.load_cache() or time.time() - self._refreshed_at > 86400:
            self.refresh()

    def refresh(self) -> int:
        """Re-scan the Start Menu. Returns the number of apps found."""
        entries: dict[str, AppEntry] = {}

        for row in powershell_json("Get-StartApps | Select-Object Name, AppID", timeout=60):
            name = (row.get("Name") or "").strip()
            app_id = (row.get("AppID") or "").strip()
            if not name or not app_id:
                continue
            if app_id.startswith(("http://", "https://")):
                kind = "url"
            elif "!" in app_id or app_id.startswith("Microsoft.AutoGenerated"):
                kind = "packaged"
            else:
                kind = "win32"
            # Prefer the first entry for a name; duplicates (e.g. a Store and a
            # desktop Spotify) resolve to whichever Windows lists first.
            entries.setdefault(name.casefold(), AppEntry(name=name, app_id=app_id, kind=kind))

        with self._lock:
            self._entries = sorted(entries.values(), key=lambda e: e.name.casefold())
            self._refreshed_at = time.time()
            self._persist()

        log.info("indexed %d apps", len(self._entries))
        return len(self._entries)

    def _persist(self) -> None:
        APP_INDEX_PATH.write_text(
            json.dumps(
                {
                    "refreshed_at": self._refreshed_at,
                    "entries": [asdict(e) for e in self._entries],
                },
                indent=1,
            ),
            encoding="utf-8",
        )

    # -- lookup ------------------------------------------------------------

    @property
    def entries(self) -> list[AppEntry]:
        with self._lock:
            if not self._entries:
                self.ensure()
            return list(self._entries)

    def _apply_alias(self, query: str) -> str:
        aliases = {k.casefold(): v for k, v in load().app_aliases.items()}
        return aliases.get(query.strip().casefold(), query)

    def search(self, query: str, limit: int = 8) -> list[tuple[AppEntry, float]]:
        """Fuzzy-match ``query`` against app names, best first."""
        query = self._apply_alias(query).strip()
        if not query:
            return []

        candidates = self.entries
        by_name = {e.name: e for e in candidates}

        matches = process.extract(
            query,
            list(by_name),
            scorer=fuzz.WRatio,
            limit=limit * 4,
            processor=lambda s: s.casefold(),
        )

        scored: list[tuple[AppEntry, float]] = []
        for name, score, _ in matches:
            entry = by_name[name]
            # A leading-substring hit ("nvidia" -> "NVIDIA App") is a much
            # stronger signal than WRatio alone gives it.
            if entry.name.casefold().startswith(query.casefold()):
                score += 12
            if entry.is_junk:
                score -= 45
            if entry.kind == "url":
                score -= 20
            scored.append((entry, min(score, 100.0)))

        scored.sort(key=lambda pair: pair[1], reverse=True)
        return scored[:limit]

    def resolve(self, query: str, threshold: float = 62.0) -> AppEntry | None:
        results = self.search(query, limit=3)
        if results and results[0][1] >= threshold:
            return results[0][0]
        return None

    # -- launching ---------------------------------------------------------

    def launch(self, entry: AppEntry) -> None:
        """Launch via the shell, inheriting this process's (normal) privileges.

        ``explorer.exe shell:AppsFolder\\<AppID>`` is the one path that works for
        packaged and Win32 apps alike. Because it hands off to Explorer, the new
        process is owned by the user's shell -- never elevated.
        """
        if entry.kind == "url":
            os.startfile(entry.app_id)  # noqa: S606 - opening a URL in the default browser
            return

        subprocess.Popen(
            ["explorer.exe", f"shell:AppsFolder\\{entry.app_id}"],
            creationflags=NO_WINDOW,
            close_fds=True,
        )

    def launch_path(self, path: str | Path) -> None:
        """Open an arbitrary file, folder, or URL with its default handler."""
        os.startfile(str(path))  # noqa: S606


index = AppIndex()
